# Ruby 2.0
#
# Version 0.0.1

FROM bpinto/ruby-build
#MAINTAINER ..TODO..

# Set ruby version
RUN \
  export RUBY_VERSION=2.0.0-p353 ;\
  echo "export RUBY_VERSION=$RUBY_VERSION" >> /.profile ;\
  echo "export PATH=/usr/local/lib/$RUBY_VERSION/bin:$PATH" >> /.profile

# Install ruby
RUN \
  source /.profile ;\
  ruby-build $RUBY_VERSION /usr/local/lib/$RUBY_VERSION

# Configure gem installations
RUN \
  source /.profile ;\
  echo "gem: --no-rdoc --no-ri" > ~/.gemrc

# Install bundler
RUN \
  source /.profile ;\
  gem install bundler
