# Ruby-build
#
# Version 0.0.1

FROM centos
#MAINTAINER ..TODO..

# Install git
RUN yum install -y git

# Install ruby dependencies
RUN yum install -y gcc openssl-devel

# Install ruby-build
RUN git clone https://github.com/sstephenson/ruby-build.git /usr/local/src/ruby-build
RUN cd /usr/local/src/ruby-build && ./install.sh

